## GLOBAL VARIABLES

# Define a shared seed so changes can be compared
SEED = 1738

MAX_STEPS = 15000
HEIGHT_DESIRED = 2.0

SENSOR_RADIUS_METERS = 30

# in meters from center
WORLD_X_MIN = -100.0
WORLD_X_MAX = 100.0
WORLD_Y_MIN = -100.0
WORLD_Y_MAX = 100.0

GRID_ROWS = 200
GRID_COLS = 200

CELLS_PER_METER = min((GRID_ROWS / (WORLD_Y_MAX - WORLD_Y_MIN)), (GRID_COLS / (WORLD_X_MAX - WORLD_X_MIN)))

SENSOR_RADIUS_CELLS = int(SENSOR_RADIUS_METERS * CELLS_PER_METER)
